### ISSUE TITLE
Crash on Big Sur

### ISSUE THREAD

**Issue by ReekyStive** [maculateConception/aural-player#23] opened 2021-02-08 21:43 UTC
I'm using MacBook Air with Apple M1 chip, macOS Big Sur 11.2 (the latest stable version currently).

I tried [Aural 2.2.0](https://github.com/maculateConception/aural-player/releases/tag/2.2.0) (the latest release currently) and [Aural 2.1.0](https://github.com/maculateConception/aural-player/releases/tag/2.1.0), and they both crash when opened.

This is the crash log when I open the 2.2.0 version, I hope they contain useful information:

[crash_log.log](https://github.com/maculateConception/aural-player/files/5946984/crash_log.log)

**Comment by maculateConception** [comment] 2021-02-09 14:06
Thank you for the issue report and the crash log.

I'll be honest with you ... I don't have access to an M1 Mac, and will not be able to reproduce this issue, so it is highly unlikely that I will be able to fix it.

Thanks again for your interest in the project.

**Comment by ReekyStive** [comment] 2021-02-09 15:14
I noticed this in the README:

[doesnt-work-on-macos-big-sur-yet](https://github.com/maculateConception/aural-player#doesnt-work-on-macos-big-sur-yet)

Maybe it's not the compatibility issue related to M1, but the issue related to Big Sur?

**Comment by ReekyStive** [comment] 2021-02-09 15:36
> I noticed this in the README:
> 
> [doesnt-work-on-macos-big-sur-yet](https://github.com/maculateConception/aural-player#doesnt-work-on-macos-big-sur-yet)
> 
> Maybe it's not the compatibility issue related to M1, but the issue related to Big Sur?

Updated README. #24

**Comment by maculateConception** [comment] 2021-02-09 15:59
Thanks, that's a good point.

I have added in your README changes, slightly reworded.

**Comment by maculateConception** [comment] 2021-02-09 16:06
Hey, I have a working development build that runs on macOS Big Sur. Do you wanna try it out ?

Obviously, it's not a release build, so expect it not to be perfect. But at least you can get it running, and it will help me find out if the issue is indeed with M1 or with Big Sur.

The UI is a bit messed up ... text misaligned, etc. But it definitely runs on macOS Big Sur.

I can upload the Big Sur dev build and share the link with you.

**Comment by ReekyStive** [comment] 2021-02-09 16:22
Of course, I am willing to try.

**Comment by maculateConception** [comment] 2021-02-09 16:36
[Here you go!](https://github.com/maculateConception/aural-player/releases/tag/2.3.0_dev)

Let me know if it works. I'm curious. Thanks.

**Comment by ReekyStive** [comment] 2021-02-09 16:56
It works on my M1 MacBook Air running Big Sur.

<img width="1177" alt="Screen Shot 2021-02-10 at 00 53 16" src="https://user-images.githubusercontent.com/26853900/107398327-7b8c4e80-6b3a-11eb-9c36-4e41861aea7e.png">

 Looking forward to the stable release!

**Comment by maculateConception** [comment] 2021-02-09 16:58
Thank you Sir / Madam ! That is great news :) Yes, I will try and get that release out as soon as I can.

Hey, your image shows your serial number. You should erase it from the image so no one can see it.

**Comment by ReekyStive** [comment] 2021-02-09 17:05
It works on my M1 MacBook Air running Big Sur.

Screen Shot 2021-02-10 at 00 53 16

Looking forward to the stable release!
<img width="1680" alt="Screen Shot 2021-01-31 at 06 45 57" src="https://user-images.githubusercontent.com/26853900/107399707-015cc980-6b3c-11eb-86d3-d25f5e25205f.png">

**Comment by ReekyStive** [comment] 2021-02-09 17:16
I have deleted it. Thank you for your reminder, I didn't notice it.

Original reply:

> It works on my M1 MacBook Air running Big Sur.
> [deleted image]
> Looking forward to the stable release!

**Comment by maculateConception** [comment] 2021-02-14 07:52
Hi, version [2.3.0](https://github.com/maculateConception/aural-player/releases/tag/2.3.0) has been released. Runs great on Big Sur !

Thanks very much for your help with this.

I'm now closing this issue.

**Closed by maculateConception** 2021-02-14 07:52 UTC
