### ISSUE TITLE
FLAC Support

### ISSUE THREAD

**Issue by jicksta** [maculateConception/aural-player#7] opened 2018-08-25 13:43 UTC
This is an ideal audio player for me in many ways, except that my main use-case involves mostly FLAC audio. Sorry, I don't have the time or stack proficiency to add this in myself.

I noticed Aural Player uses `AVFoundation` for playback. I couldn't find anything online about FLAC with `AVFoundation`, so I assume that FLAC support would entail the use of a third-party library. This may involve re-writing of or indirection around the currently used `AVFoundation` APIs, so I understand if this is out-of-scope for a minimalist project. As for third-party audio engines, my cursory searching led me to [OrigamiEngine](https://github.com/ap4y/OrigamiEngine), which also seems to standardize metadata access across formats too.

Thanks for the work on Aural Player so far! If this is out-of-scope, perhaps someone in the community could take this up?

**Comment by maculateConception** [comment] 2018-08-26 01:40
Hi @jicksta ,

Thanks for your great feedback on and interest in the Aural Player project.

Yes, you're right, this was intended as a "minimalist" project, not as a comprehensive audio player that plays everything. From what you've said about FLAC and from what I know, that definitely seems like it would require too much reworking to support, so I will have to pass on the responsibility for now.

I would love for someone to fork Aural Player and add the FLAC support (another good one to have would be WMA).

Best regards,
maculateConception

**Comment by maculateConception** [comment] 2018-12-13 04:14
Hi @jicksta ,

I discovered today that my player can, in fact, play FLAC files, right out of the box without any special modifications.

I have also figured out how to include LibAV in my player, which can transcode between other formats like Ogg, Vorbis, WMA, etc, and happen to be adding that support right now. So, pretty soon, I will put out a release of my app that can play damn near everything.

Thought I'd let you know because you had mentioned that Aural Player is an ideal player for your needs.

Cheers !

**Comment by grogcw** [comment] 2018-12-13 04:14
Hi !
I read this thread, and I'd like to back jicksta up on this neat feature :)

Cheers !

**Comment by maculateConception** [comment] 2018-12-13 04:39
Hi grogcw, thanks for the message.

Yes, my player can definitely play FLAC files. I was unaware of this before, but today, accidentally discovered this :)

I will soon put out a release that allows users to add FLAC files to the playlist.

Cheers !

**Comment by maculateConception** [comment] 2018-12-13 12:44
Cool ! Thanks for the great feedback.

BTW, I realized that I'm running macOS 10.14, and native FLAC support was introduced in 10.13 (High Sierra). So, Aural Player will natively play FLAC on High Sierra and Mojave. If you have an older OS, it will now transcode it to another format like AIFF and play the transcoded file.

So, either way, FLAC support is coming for sure :)

Thanks again, and yes, do file that issue.

**Comment by maculateConception** [comment] 2018-12-27 03:02
> I'm glad to read that ! I started using your player yesterday and I love it already !
> 
> I'd like it to be a little more compact width-wise tho, but I'll open another issue regarding the GUI.
> 
> Please continue your great work, you're on the right track !
> 
> Cheers !

Hi, I've been working hard to get the new release out, that will play many new formats including FLAC. At this point, the implementation is pretty much done and I am doing extensive testing. So, you can expect a release some time in the next few days.

**Comment by maculateConception** [comment] 2018-12-31 10:05
Released with support for FLAC and many more formats !
[Download here:](https://github.com/maculateConception/aural-player/releases/latest)

**Closed by maculateConception** 2018-12-31 10:05 UTC
