### ISSUE TITLE
spacebar crash on macbook

### ISSUE THREAD

**Issue by honk69** [maculateConception/aural-player#31] opened 2021-11-08 20:04 UTC
Hi,
every time i press the spacebar to start or pause Aural, it crashes.

I'm running it on a macbbook (intel i5) with OS 12.0.1

**Comment by maculateConception** [comment] 2021-11-08 20:13
Hi, thanks for reporting this issue.

Can you please include information about the file you were trying to play / pause. What audio format ?

Did this happen immediately after starting the app ? Or after using it for a while ?

Are there any crash logs / reports you can include ?

Thanks.

Please note that I'm currently very busy with another project and won't be able to look into this for a while.

As a temporary workaround, you might want to try using an older version of Aural Player. Go to the Releases page and try downloading an older version. That might work.

**Comment by honk69** [comment] 2021-11-08 20:20
I tried it with different audio files… mainly mp3, but it happens with every kind of file.
Aural runs fine until i press the spacebar and it doesn't matter when I do, Aural immediately crashes.

I looked for a crash log, but can't find any… neither do i get a message. Seems like it just quits instead of play/pause

**Comment by maculateConception** [comment] 2021-11-08 20:24
Ok, thanks. That's very strange.

Yeah, I would try using an older version for now, just in case.

**Comment by maculateConception** [comment] 2021-11-08 20:29
Another idea - can you try using the pause media key on your keyboard instead of the spacebar ? Does that also cause a crash ?

**Comment by honk69** [comment] 2021-11-08 20:53
I have no media keys on my macbook and Aural is not using the Touch Bar or showing any keys there… ;)

**Comment by maculateConception** [comment] 2021-11-08 21:02
<img width="620" alt="Screenshot 2021-11-09 at 2 31 07 AM" src="https://user-images.githubusercontent.com/30028539/140817539-3762227c-5876-4c9e-8dc0-5ef862f21b80.png">

**Comment by honk69** [comment] 2021-11-09 04:25
ok, found the keys… no problems when i use them, but still quits after using the space bar ;)

**Comment by maculateConception** [comment] 2021-11-09 08:41
The pause touch bar key is just a media key ... try sending a pause media key event with Apple Script.

As I said, I won't be able to look into the space bar issue for a while, so please use this as a workaround in the meantime.

**Comment by maculateConception** [comment] 2021-12-18 09:46
Without a crash log, I really cannot do anything about this. I'm closing this issue for now. If you happen to get a crash log, do reopen it with the attached log and I will take a look.

**Closed by maculateConception** 2021-12-18 09:46 UTC

**Comment by maculateConception** [comment] 2022-01-23 08:24
Hello, are you using Better Touch Tool on your system ? Another Aural user had the same problem as you.

He recommends keeping Better Touch Tool open while using Aural or re-opening it if it is already running. It seems to work for him when BTT is open or reopened.

Just wanted to pass on this information to you in the hope that it helps.

We were unable to determine the cause of this crash, as it leaves no log messages behind.
