### ISSUE TITLE
Keyboard shortcuts kill the app.

### ISSUE THREAD

**Issue by janmotl** [maculateConception/aural-player#32] opened 2022-01-09 18:34 UTC
Pressing ␣  or ⌘M kills the application. 
Corresponding mouse clicks work OK.
Some other keyboard shortcuts like ⌘→ work OK as well.

**Comment by maculateConception** [comment] 2022-01-11 07:50
Hi, can you please share some information to help me debug this issue.

1. Operating system version (exact version - x.y.z).
2. Hardware (M1 or Intel ?)
3. Aural Player version (menu: Aural > About Aural)
4. Go to your **Music/aural** directory and look for a file called **aural.log**. Please attach that file here if possible.
5. Does any particular sequence of actions trigger the problem ? For example - I first added files to the playlist, then hit the play button then hit the space bar.

Thanks !

**Comment by janmotl** [comment] 2022-01-11 11:12
> Operating system version (exact version - x.y.z).

10.14.6 (18G103)

> Hardware (M1 or Intel ?)

Intel

> Aural Player version (menu: Aural > About Aural)

3.5.0

> Go to your Music/aural directory and look for a file called aural.log. Please attach that file here if possible.

There is no log file. Only `state.json` and `musicBrainzCache`. Do I have to do something to invoke the creation of the log file?
 
> Does any particular sequence of actions trigger the problem ? For example - I first added files to the playlist, then hit the play button then hit the space bar.

No sequence is necessary. I just open Aural. Press spacebar. Aural dies.

**Comment by maculateConception** [comment] 2022-01-11 13:57
Thanks for the info.

It's strange that there is no log file. You don't have to do anything, it should have been created automatically.

I will take a look and try to fix it soon. I may need more information, but for now I have enough to get started.

Cheers !

**Comment by LesterJitsi** [comment] 2022-01-17 16:58
Just FYI, I'm running Aural 3.5.0 on a similar environment (MacBook Air Retina, 13-inch, 2019, 10.14.6 (**18G9323**) and I can not reproduce @janmotl's issue, everything works. Compared to 18G103, I have installed all security updates for Mojave 2019-2021. I have also allowed Aural to control the computer in _System Prefs > Security & Privacy > Accessibility_, as I was asked to do on first Aural opening. I do have the log file. I wonder whether denying the request to control the computer limits Aural's writing and executing permissions in the Home folder.

**Comment by janmotl** [comment] 2022-01-17 17:57
@LesterJitsi I tested Aural with the accessibility permission turned on/off. It crashes in both scenarios. 

Since Aural worked well under my guest account, the crashes are because of my user profile. Do you have some idea what to test?

**Comment by LesterJitsi** [comment] 2022-01-17 18:29
@janmotl Did you remove Aural from the authorized apps or just unchecked the radio button? On my machine just unchecking the button doesn't work. Click on the minus icon.

On your guest account, when you start Aural,  are you asked to allow the app to control the computer or not? If you're not then the many security updates you didn't install may be relevant.

To be honest any advice about your user library would be a shot in the dark. You may want to trash Aural caches and preferences. I'd check also _you/Music/aural_  permissions: do you have permission to write?

**Comment by maculateConception** [comment] 2022-01-17 23:19
@LesterJitsi - Thanks very much for sharing that information and helping debug this issue. Appreciate it.

@janmotl - The issue is not reproducible on Big Sur, which is the system I am running on my main machine. I will have to see if I have Mojave installed on my old MBPro. If not, I may not be able to reproduce this exact issue.

Aural v3.5.0 was built using the latest Xcode v13.x, and sometimes newer Xcode versions produce app bundles that behave weirdly on older systems like Mojave in this case.

Also, I am in the process of planning, designing, and developing an overhauled revamped Aural Player v4.0 which will end support for all older systems before Big Sur, so I am not planning to support Mojave / Catalina going forward. This will allow the app to use new and improved APIs, plus I'm a one-man team and I have very limited time and resources for testing (hardware / software).

I have been very busy with my full-time job, but I will try to reproduce it on my old MBPro and hopefully come up with a fix, although it sounds like it is hard to reproduce this issue, from what Lester said.

**Comment by maculateConception** [comment] 2022-01-17 23:23
@janmotl  - In response to what @LesterJitsi suggested, you may want to try deleting your ~/Music/aural folder, which will delete your state.json file (which contains most of the saved app settings).

But, I'm really not sure if that will help in this particular case. Worth a try.

Hey, what about the play / pause media key ? Can you try using that ? Does that also cause a crash ?

**Comment by maculateConception** [comment] 2022-01-17 23:28
FYI, another Aural user encountered this issue on macOS Monterey:

https://github.com/maculateConception/aural-player/issues/31

**Comment by janmotl** [comment] 2022-01-18 06:23
Using the play / pause media key does not result in crash.
Using the menu bar Playback>Pause does not result in crash.
Deleting ~/Music/aural does not fix the crashes.
Aural 1.7.0 works fine. Aural 2.0.0 crashes.

> Did you remove Aural from the authorized apps or just unchecked the radio button? On my machine just unchecking the button doesn't work. Click on the minus icon.

First, I was running Aural without the authorization. Only later on I authorized it.

> On your guest account, when you start Aural, are you asked to allow the app to control the computer or not? If you're not then the many security updates you didn't install may be relevant.

I got asked to allow the app to control the computer.

The current workaround that I use: Intercept space bar presses in Aural and invoke the play / pause from the menu bar.

**Comment by maculateConception** [comment] 2022-01-21 20:08
Hi, I tried to run my old laptop which has Mojave on it but it won't start up (it's 12 years old and probably dead).

I also tried reproducing the issue on Big Sur and Monterey, but was never able to reproduce it.

Now, the only thing I can offer you is - if you would like, I can do a Zoom call with you and help you troubleshoot the issue, because I really need more real-time context. I cannot do anything without more information.

Let me know if you would like to do a short meeting via Zoom to troubleshoot this issue. Otherwise, I will have to close it.

**Comment by maculateConception** [comment] 2022-01-22 22:02
What time zone are you in and what time works for you ? I'm in GMT+5:30.

If you give me a time and time zone, I'll set up a meeting and give you the link.

**Comment by janmotl** [comment] 2022-01-23 04:54
I'm in GMT+1:00. Hence, I propose to meet today anytime between 7:00 and 9:00 of my local time.

**Comment by maculateConception** [comment] 2022-01-23 05:09
Ok, scheduled for 8 am your time. See details below:

------------------------------------

Kartik Venugopal is inviting you to a scheduled Zoom meeting.

Join Zoom Meeting
https://us05web.zoom.us/j/81850480062?pwd=dktxdzAvMGJ0VW9hUDJzWitCVHBzUT09

Meeting ID: 818 5048 0062
Passcode: 1mUkZ2

**Comment by maculateConception** [comment] 2022-01-23 07:45
Meeting Summary:

We were unable to determine the cause of the crash as there is no macOS crash dialog / report, and aural.log does not show any helpful error messages.

There is an unrelated bug in v3.5.0 that causes the log file not to be generated. This will be fixed in v3.6.0 or v3.5.1.

Roughly half of the Playback menu items are causing this crash, and the other half are working.

Interestingly, it works fine on his other system running macOS Catalina. The issue must be specific to his macOS Mojave system / user profile.

Jan is using, and will continue using, a workaround - intercepting and redirecting keystrokes.

I am closing this issue, as there is nothing further to be done.

**Closed by maculateConception** 2022-01-23 07:45 UTC
Labels: bug, help wanted

**Comment by janmotl** [comment] 2022-01-23 08:03
@maculateConception Thank you for your help even though we didn't solve it. 

Btw., just now, the keyboard shortcuts started to work once I _reopened_ Better Touch Tool (BTT) 3.5 (for the purpose of the meeting, I closed it). Note that once I _close_ BTT, the issue reapers...

I wasn't able to reproduce the issue on another computer with BTT 3.728.

If someone else encounters the same issue, this could be a hint. But my workaround suffices for me.

**Comment by maculateConception** [comment] 2022-01-23 08:15
@janmotl Thanks for reporting that, Jan ! It was nice to meet with you earlier.

BTW, I have just released v3.5.1 which fixes the log generation bug and another unrelated color scheming bug.

Please download and use that instead ... in the future, if there are other issues, you'll have the log file :-)

Cheers !
