### ISSUE TITLE
Sorting when adding folders to playlist not alphanumerical

### ISSUE THREAD

**Issue by shoopdawoop** [maculateConception/aural-player#29] opened 2021-06-29 08:07 UTC
When adding folders to the playlist on macOS the playlist is not sorted by filename or ID-tag track number, which I would have expected.

Feature or missing feature? ;D

**Comment by maculateConception** [comment] 2021-06-29 09:04
Hi, thanks for your question.

Are you referring to
1 - The ***entire*** playlist not being sorted when adding folders / tracks ?
OR
2 - The ***new folders / tracks*** not being added in alphanumeric order ?

Please clarify.

By design, when you add new folders / tracks, only the new items will be added in an alphanumeric order (from what I remember). But it won't sort the entire playlist. Of course, if you want to sort the ***entire*** playlist, there is a sort option (see button with up down arrow icon).

In other words, even though you can sort the playlist whenever you want, the playlist won't ***remain sorted***. This is by design, because users are allowed to re-order tracks at will. So, in order for the playlist to ***remain sorted***, you would have to prevent the user from reordering tracks manually, which would not be a good user experience.

One thing that ***maybe*** can be done is adding a new option to "Sort entire playlist when new tracks are added", but I don't know how useful that would be. I would have to think about this.

**Comment by shoopdawoop** [comment] 2021-06-30 16:57
> 2 - The new folders / tracks not being added in alphanumeric order ?

I am referring to this only.

When I add multiple files to the playlist (empty or not) by selecting them in the Finder and dropping them on the playlist, the files do get added in alphanumerical order.

But when I drag and drop a folder that contains the files, the sort order of these files is not alphanumerical.

So far I have only tested this on macOS 10.13.6 btw.

**Comment by maculateConception** [comment] 2021-06-30 19:49
Thanks for getting back to me.

Ok, I was able to reproduce the issue on my system, and I have developed a fix for it. For some reason, Finder does not send the files in sorted order when dragging a folder, but does sort them when sending the files themselves. So, the solution is for the playlist itself to sort them before adding them. I thought this was already being done, but it was not.

I will release the fix (along with a new feature) soon in version 3.2.0. You can upgrade to 3.2.0 when it comes out and try it out to see that it has been fixed.

Thank you for reporting this issue ! Cheers.
- mC

**Comment by maculateConception** [comment] 2021-07-01 22:45
The fix has been released in [version 3.2.0](https://github.com/maculateConception/aural-player/releases/tag/3.2.0). This issue is now closed.

**Closed by maculateConception** 2021-07-01 22:45 UTC
