### ISSUE TITLE
Microphone is activated as soon as app starts, not just when recording starts

### ISSUE THREAD

**Issue by sriegler** [maculateConception/aural-player#18] opened 2020-08-31 08:35 UTC
As soon as the app starts, access to the microphone/input is requested and the configured microphone is activated.

This should only happen when one clicks the recording start button and not already from the start of the app. Stopping the recording should release the input device.

**Comment by maculateConception** [comment] 2020-08-31 20:30
Thank you for reporting this issue.

Aural Player does not use the microphone at all, and so should not prompt the user for that at all. The recording feature does not use the microphone. It picks up whatever is being sent to the output device.

I think I know what the problem is. It has to do with app entitlements. I will fix this in the next release.

**Comment by maculateConception** [comment] 2021-06-17 19:52
Not sure if this issue is relevant anymore. I have not encountered this issue. If it persists for you, please reopen the issue. I am closing it for now.

**Closed by maculateConception** 2021-06-17 19:52 UTC
