### ISSUE TITLE
playlist sort popup doesn't remember selected sorting method

### ISSUE THREAD

**Issue by minusf** [maculateConception/aural-player#22] opened 2021-01-19 15:31 UTC
aural 2.2.0:

1. load a playlist
2. open the sort popup, select any method except "Track name"
3. reopen sort popup, "Track name" is selected.

**Comment by maculateConception** [comment] 2021-02-05 13:27
Hi, thanks for the bug report.

The behavior you pointed out is how it was intended to behave. I didn't think it would be much of an inconvenience for users, because I assumed that sorting doesn't occur very often.

But, I'm guessing you find that inconvenient, so I will consider this a bug and keep it in mind for when I return to working on the project.

Cheers :)

**Comment by maculateConception** [comment] 2021-02-14 07:53
This issue has been fixed in release [v2.3.0](https://github.com/maculateConception/aural-player/releases/tag/2.3.0).

Thanks again.

**Closed by maculateConception** 2021-02-14 07:53 UTC
